import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";



const outfit = Outfit({ subsets: ["latin"], weight: ["200", "500"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-white`}
      >
        <div className="flex h-screen w-screen overflow-hidden">
          <Navbar />
          <main className="flex-1 overflow-y-scroll h-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
